package com.scolastico.dataviewer.gui;

import com.formdev.flatlaf.intellijthemes.FlatDarkFlatIJTheme;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParser;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URLDecoder;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import javax.imageio.ImageIO;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rsyntaxtextarea.Theme;

public class Main {

  Gson gsonPretty = new GsonBuilder().setPrettyPrinting().disableHtmlEscaping().create();
  Gson gsonNormal = new GsonBuilder().disableHtmlEscaping().create();

  private JTextField raw;
  private RSyntaxTextArea json;
  private JButton rawToJson;
  private JButton jsonToRaw;
  private JPanel MainFrame;

  public static void main(String[] args) {
    FlatDarkFlatIJTheme.install();
    JFrame frame = new JFrame("scolasti.co - Data Viewer and Converter");
    try {
      frame.setIconImage(ImageIO.read(ClassLoader.getSystemResource("icon.png")));
    } catch (Exception ignored) {
    }
    frame.setSize(500, 500);
    frame.setMinimumSize(new Dimension(520, 540));
    frame.setContentPane(new Main().MainFrame);
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    frame.pack();
    frame.setLocationRelativeTo(null);
    frame.setVisible(true);
  }

  public Main() {
    $$$setupUI$$$();
    rawToJson.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {
        String rawText = "Error while trying to compile!";
        try {
          rawText = gsonPretty.toJson(
              JsonParser.parseString(
                  URLDecoder.decode(raw.getText(), StandardCharsets.UTF_8)
              )
          );
        } catch (Exception ignored) {
        }
        json.setText(rawText);
      }
    });
    jsonToRaw.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {
        String jsonText = "Error while trying to compile!";
        try {
          jsonText = URLEncoder.encode(
              gsonNormal.toJson(
                  JsonParser.parseString(json.getText())
              )
              , StandardCharsets.UTF_8);
        } catch (Exception ignored) {
        }
        raw.setText(jsonText);
      }
    });
  }


  private void createUIComponents() {
    json = new RSyntaxTextArea();
    try {
      Theme theme = Theme.load(ClassLoader.getSystemResourceAsStream("darkEditorTheme.xml"));
      theme.apply(json);
    } catch (Exception ignored) {
    }
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    createUIComponents();
    MainFrame = new JPanel();
    MainFrame.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    final JPanel panel1 = new JPanel();
    panel1.setLayout(new GridLayoutManager(5, 1, new Insets(5, 5, 5, 5), -1, -1));
    MainFrame.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(500, 500), new Dimension(500, 500), null, 0, false));
    final JLabel label1 = new JLabel();
    label1.setText("RAW:");
    panel1.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    final JLabel label2 = new JLabel();
    label2.setText("JSON:");
    panel1.add(label2, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    final JScrollPane scrollPane1 = new JScrollPane();
    panel1.add(scrollPane1, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    json.setSyntaxEditingStyle("text/json");
    json.setTabSize(2);
    json.setTabsEmulated(true);
    scrollPane1.setViewportView(json);
    final JPanel panel2 = new JPanel();
    panel2.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
    panel1.add(panel2, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    final JPanel panel3 = new JPanel();
    panel3.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    panel2.add(panel3, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    rawToJson = new JButton();
    rawToJson.setFocusCycleRoot(true);
    rawToJson.setText("Raw  to  Json");
    panel3.add(rawToJson, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    final JPanel panel4 = new JPanel();
    panel4.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    panel2.add(panel4, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    jsonToRaw = new JButton();
    jsonToRaw.setFocusCycleRoot(true);
    jsonToRaw.setText("Json  to  Raw");
    panel4.add(jsonToRaw, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    raw = new JTextField();
    panel1.add(raw, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return MainFrame;
  }

}
